web:
  build: .
  command: npm start
  volumes:
    - .:/usr/src/app
  ports:
    - "3000:3000"
  environment:
    PORT: 3000 # this is optional, allows express to use process.env.PORT instead of a raw 3000
